SET(CMAKE_MODULE_PATH ${STM32_CMAKE_DIR} ${CMAKE_MODULE_PATH})
STRING(REGEX REPLACE "\\\\" "/" MYPATH ${UNITY_LIB_PATH}) 


		LIST(APPEND UNITY_SOURCES ${MYPATH}/unity/unity.cpp)
		LIST(APPEND UNITY_SOURCES ${MYPATH}/unity/unity_assertion.cpp)
		LIST(APPEND UNITY_SOURCES ${MYPATH}/unity/unity_fixture.cpp)
#FORCE_INCLUDE
#LIST(APPEND FORCE_INCLUDE void/platform_specific.h)




INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(UNITY DEFAULT_MSG UNITY_SOURCES)

